spring:
    datasource:
        url: jdbc:postgresql://localhost:3306/cars
        username: root
        password: 12345

    jpa:
        generate-ddl: true
        properties:
            hibernate:
                jdbc:
                    time_zone: UTC
